<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-17T18:30:43 EET" name="Default suite" finished-at="2024-11-17T18:31:13 EET" duration-ms="30524">
    <groups>
    </groups>
    <test started-at="2024-11-17T18:30:43 EET" name="Default test" finished-at="2024-11-17T18:31:13 EET" duration-ms="30524">
      <class name="MyTestCases">
        <test-method is-config="true" signature="mySetUp()[pri:0, instance:MyTestCases@35cabb2a]" started-at="2024-11-17T18:30:43 EET" name="mySetUp" finished-at="2024-11-17T18:30:43 EET" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetUp -->
        <test-method signature="clickTowNumRandom()[pri:0, instance:MyTestCases@35cabb2a]" started-at="2024-11-17T18:30:43 EET" name="clickTowNumRandom" finished-at="2024-11-17T18:31:13 EET" duration-ms="30423" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [86420] but found [7894561230]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [86420] but found [7894561230]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at MyTestCases.clickTowNumRandom(MyTestCases.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickTowNumRandom -->
      </class> <!-- MyTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
